services:

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/medusa-db-yndhl
    networks:
        - backend

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    networks:
        - backend
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh # Montage du script
      - ./seed-bdd:/seed-bdd # Montage du dossier seed
    command: ["sh", "/docker-entrypoint-initdb.d/init-db.sh"] # Remplacer la commande de démarrage par défaut
volumes:
  postgres-data:

networks:
    backend:

